#!/usr/bin/env bash
# Install Prometheus + Grafana (kube-prometheus-stack) and wire them to Ray:
#   1. installs the chart into prometheus-system with infra/monitoring values,
#   2. applies PodMonitors that scrape the Ray head and workers,
#   3. copies the Grafana dashboards generated by the running Ray head into
#      ConfigMaps so Grafana loads the exact versions the Ray dashboard embeds.
# Run after the RayCluster is up (deploy.sh does this). Safe to re-run.
#
# Configuration (environment variables, all optional):
#   CLUSTER_NAME        kind cluster name                          (default: ray)
#   RAY_NAMESPACE       namespace of the RayCluster                (default: ray)
#   KPS_VERSION         kube-prometheus-stack chart version        (default: 91.7.1)
set -euo pipefail

INFRA_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CLUSTER_NAME="${CLUSTER_NAME:-ray}"
RAY_NAMESPACE="${RAY_NAMESPACE:-ray}"
KPS_VERSION="${KPS_VERSION:-91.7.1}"
KUBE_CONTEXT="kind-${CLUSTER_NAME}"
MON_NS=prometheus-system

log()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
fail() { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }
kc()   { kubectl --context "$KUBE_CONTEXT" "$@"; }

log "Installing kube-prometheus-stack ${KPS_VERSION} into ${MON_NS}"
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts --force-update >/dev/null
helm repo update prometheus-community >/dev/null
helm upgrade --install prometheus prometheus-community/kube-prometheus-stack \
  --version "$KPS_VERSION" \
  --kube-context "$KUBE_CONTEXT" \
  --namespace "$MON_NS" --create-namespace \
  --values "${INFRA_DIR}/monitoring/values-kube-prometheus-stack.yaml" \
  --wait --timeout 10m >/dev/null

log "Applying Ray PodMonitors"
kc apply -f "${INFRA_DIR}/monitoring/ray-podmonitors.yaml" >/dev/null

log "Loading Ray Grafana dashboards from the head pod"
head_pod="$(kc -n "$RAY_NAMESPACE" get pod -l ray.io/node-type=head -o jsonpath='{.items[0].metadata.name}')"
[[ -n "$head_pod" ]] || fail "No Ray head pod found in namespace $RAY_NAMESPACE"
# Paths go inside `sh -c` strings: Git Bash would rewrite a bare /tmp/... argument into a Windows path.
dash_dir=/tmp/ray/session_latest/metrics/grafana/dashboards
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
dashboards="$(kc -n "$RAY_NAMESPACE" exec "$head_pod" -- sh -c "ls ${dash_dir}")"
[[ -n "$dashboards" ]] || fail "No Grafana dashboards found in ${dash_dir} on ${head_pod}"
for f in $dashboards; do
  kc -n "$RAY_NAMESPACE" exec "$head_pod" -- sh -c "cat ${dash_dir}/${f}" > "${tmp}/${f}"
  name="ray-dashboard-$(basename "$f" .json | tr '_' '-')"
  # Server-side apply: the larger dashboards exceed the client-side annotation limit.
  kc -n "$MON_NS" create configmap "$name" --from-file="${tmp}/${f}" --dry-run=client -o yaml \
    | kc label --local -f - grafana_dashboard=1 -o yaml \
    | kc apply --server-side --force-conflicts -f - >/dev/null
  echo "    ${f}"
done

# One endpoint per Ray pod (8080) plus the head's autoscaler and dashboard endpoints.
pods="$(kc -n "$RAY_NAMESPACE" get pods -l ray.io/is-ray-node=yes -o name | wc -l)"
expected=$((pods + 2))
log "Waiting for Prometheus to scrape all ${expected} Ray metrics endpoints"
up=0
for _ in $(seq 1 60); do
  up="$(curl -fsS 'http://127.0.0.1:9090/api/v1/query?query=count(up%7Bnamespace%3D%22'"$RAY_NAMESPACE"'%22%7D%3D%3D1)' 2>/dev/null \
    | sed -n 's/.*"value":\[[^,]*,"\([0-9]*\)".*/\1/p')"
  if [[ -n "$up" && "$up" -ge "$expected" ]]; then
    log "Prometheus is scraping ${up}/${expected} Ray metrics endpoints"
    exit 0
  fi
  sleep 5
done
fail "Only ${up:-0}/${expected} Ray targets are up. Check http://127.0.0.1:9090/targets"
